#!/usr/bin/env python3
"""One registry setting → every image field that needs it.

    scripts/render-images.py <env>

Reads global.imageRegistry from environments/<env>/values.yaml (e.g.
"myproxy.bank.internal:5000") and writes environments/<env>/generated-images.yaml,
used with BOTH charts. Most images already follow global.imageRegistry; this
covers the ones whose charts don't read it:

    loki rollout-operator      docker.io/grafana/rollout-operator
    kgateway (+ its proxies)   cr.kgateway.dev/kgateway-dev/...
    External Secrets (×3)      ghcr.io/external-secrets/external-secrets

With a registry set, every image is <registry>/<upstream path>, keeping the
upstream path (grafana/grafana, kgateway-dev/envoy-wrapper,
external-secrets/external-secrets, library/memcached, ...). Configure the proxy
to serve each upstream under that path. Empty registry = upstream defaults.
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    env_dir = ROOT / "environments" / sys.argv[1]
    values = yaml.safe_load((env_dir / "values.yaml").read_text()) or {}
    reg = ((values.get("global") or {}).get("imageRegistry") or "").rstrip("/")
    out: dict = {}
    if reg:
        eso = f"{reg}/external-secrets/external-secrets"
        out = {
            "loki": {"rollout_operator": {"image": {"registry": reg}}},
            "kgateway": {"image": {"registry": f"{reg}/kgateway-dev"}},
            "external-secrets": {
                "image": {"repository": eso},
                "webhook": {"image": {"repository": eso}},
                "certController": {"image": {"repository": eso}},
            },
        }
    header = ("# GENERATED by scripts/render-images.py from global.imageRegistry in values.yaml.\n"
              f"# Registry: {reg or '(upstream registries)'}. Do not edit; re-run the script.\n")
    (env_dir / "generated-images.yaml").write_text(header + (yaml.safe_dump(out, sort_keys=False) if out else "{}\n"))
    print(f"{env_dir.relative_to(ROOT)}/generated-images.yaml: {reg or 'upstream registries'}")


if __name__ == "__main__":
    main()
